# Generated by Django 4.0.8 on 2022-10-28 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=200)),
                ('website_url', models.CharField(blank=True, max_length=200)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(default='defaults/university.jpg', upload_to='company_image/%Y/%m/%D/')),
                ('student_range', models.IntegerField(blank=True, choices=[(1, '<5000 students'), (2, '5000-15000 students'), (3, '>15000 students')], null=True)),
            ],
            options={
                'verbose_name': 'university',
                'verbose_name_plural': 'universities',
            },
        ),
        migrations.CreateModel(
            name='UniversityAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_permission', models.BooleanField(default=False)),
                ('comment_permission', models.BooleanField(default=False)),
                ('edit_profile_permission', models.BooleanField(default=False)),
                ('accept_student_application_permission', models.BooleanField(default=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university')),
            ],
            options={
                'verbose_name': 'university admin',
                'verbose_name_plural': 'university admins',
            },
        ),
    ]
