# Generated by Django 4.0.8 on 2022-10-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='university',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='university_admin_set', through='universities.UniversityAdmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='university',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to=settings.AUTH_USER_MODEL),
        ),
    ]
