from django.urls import path

urlpatterns = [
    path(
        "companies",
        CompanyList.as_view(),
        name="company-list",
    ),
    path(
        "companies/<int:pk>",
        CompanyDetail.as_view(),
        name="company-detail",
    ),
    path(
        "companies/choices",
        CompanyChoices.as_view(),
        name="job-choices",
    ),
    path(
        "company-pictures",
        CompanyPicturesList.as_view(),
        name="companypictures-list",
    ),
    path(
        "company-pictures/<int:pk>",
        CompanyPicturesDetail.as_view(),
        name="companypictures-detail",
    ),
    path(
        "company-admins",
        CompanyAdminList.as_view(),
        name="companyadmin-list",
    ),
    path(
        "company-admins/<int:pk>",
        CompanyAdminDetail.as_view(),
        name="companyadmin-detail",
    ),
    path(
        "university-admins",
        UniversityAdminList.as_view(),
        name="universityadmin-list",
    ),
    path(
        "university-admins/<int:pk>",
        UniversityAdminDetail.as_view(),
        name="universityadmin-detail",
    ),
    path(
        "universities",
        UniversityList.as_view(),
        name="university-list",
    ),
    path(
        "universities/<int:pk>",
        UniversityDetail.as_view(),
        name="university-detail",
    ),
    path(
        "university-courses",
        UniversityCourseList.as_view(),
        name="universitycourse-list",
    ),
    path(
        "university-courses/<int:pk>",
        UniversityCourseDetail.as_view(),
        name="universitycourse-detail",
    ),
    path(
        "certifications",
        CertificationList.as_view(),
        name="certification-list",
    ),
    path(
        "certifications/<int:pk>",
        CertificationDetail.as_view(),
        name="certification-detail",
    ),
]
