# Generated by Django 4.0.8 on 2022-10-28 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=200)),
                ('website_url', models.CharField(blank=True, max_length=200)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(default='defaults/company.jpg', upload_to='company_image/%Y/%m/%D/')),
                ('employee_range', models.IntegerField(choices=[(1, '1-20 employees'), (2, '21-100 employees'), (3, '101-200 employees'), (4, '201-500 employees'), (5, '501+ employees')])),
                ('industry', models.IntegerField(choices=[(1, 'Energy, Utilities and Resources'), (2, 'Government and Public Sector'), (3, 'Pharmaceuticals and Life Sciences'), (4, 'Real Estate'), (5, 'Sports Business Advisory'), (6, 'Financial Services'), (7, 'Health Services'), (8, 'Industrial Manufacturing'), (9, 'Retail and Consumer Goods'), (10, 'Technology, Media, and Telecommunications'), (11, 'Other')])),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_pictures/%Y/%m/%D/')),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='companies.company')),
            ],
            options={
                'verbose_name': 'company picture',
                'verbose_name_plural': 'company pictures',
            },
        ),
        migrations.CreateModel(
            name='CompanyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_permission', models.BooleanField(default=False)),
                ('comment_permission', models.BooleanField(default=False)),
                ('edit_profile_permission', models.BooleanField(default=False)),
                ('accept_applicants_permission', models.BooleanField(default=False)),
                ('create_jobs_permission', models.BooleanField(default=False)),
                ('view_applicants_permission', models.BooleanField(default=False)),
                ('edit_admins_permission', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name': 'company Admin',
                'verbose_name_plural': 'company Admins',
            },
        ),
    ]
