/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutKnowledgeAreasImport } from './routes/_layout/knowledge-areas'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutAssignmentsImport } from './routes/_layout/assignments'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutQuizzesIndexImport } from './routes/_layout/quizzes/index'
import { Route as LayoutAttemptsIndexImport } from './routes/_layout/attempts/index'
import { Route as LayoutAssignmentsIndexImport } from './routes/_layout/assignments/index'
import { Route as LayoutQuizzesQuizIdImport } from './routes/_layout/quizzes/$quizId'
import { Route as LayoutAttemptsAttemptIdImport } from './routes/_layout/attempts/$attemptId'
import { Route as LayoutAssignmentsAssignmentIdImport } from './routes/_layout/assignments/$assignmentId'
import { Route as LayoutQuizzesQuizIdTakeImport } from './routes/_layout/quizzes/$quizId/take'
import { Route as LayoutAttemptsAttemptIdResponsesImport } from './routes/_layout/attempts/$attemptId/responses'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutKnowledgeAreasRoute = LayoutKnowledgeAreasImport.update({
  path: '/knowledge-areas',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAssignmentsRoute = LayoutAssignmentsImport.update({
  path: '/assignments',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutQuizzesIndexRoute = LayoutQuizzesIndexImport.update({
  path: '/quizzes/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAttemptsIndexRoute = LayoutAttemptsIndexImport.update({
  path: '/attempts/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAssignmentsIndexRoute = LayoutAssignmentsIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutAssignmentsRoute,
} as any)

const LayoutQuizzesQuizIdRoute = LayoutQuizzesQuizIdImport.update({
  path: '/quizzes/$quizId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAttemptsAttemptIdRoute = LayoutAttemptsAttemptIdImport.update({
  path: '/attempts/$attemptId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAssignmentsAssignmentIdRoute =
  LayoutAssignmentsAssignmentIdImport.update({
    path: '/$assignmentId',
    getParentRoute: () => LayoutAssignmentsRoute,
  } as any)

const LayoutQuizzesQuizIdTakeRoute = LayoutQuizzesQuizIdTakeImport.update({
  path: '/take',
  getParentRoute: () => LayoutQuizzesQuizIdRoute,
} as any)

const LayoutAttemptsAttemptIdResponsesRoute =
  LayoutAttemptsAttemptIdResponsesImport.update({
    path: '/responses',
    getParentRoute: () => LayoutAttemptsAttemptIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/assignments': {
      preLoaderRoute: typeof LayoutAssignmentsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/knowledge-areas': {
      preLoaderRoute: typeof LayoutKnowledgeAreasImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/assignments/$assignmentId': {
      preLoaderRoute: typeof LayoutAssignmentsAssignmentIdImport
      parentRoute: typeof LayoutAssignmentsImport
    }
    '/_layout/attempts/$attemptId': {
      preLoaderRoute: typeof LayoutAttemptsAttemptIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/quizzes/$quizId': {
      preLoaderRoute: typeof LayoutQuizzesQuizIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/assignments/': {
      preLoaderRoute: typeof LayoutAssignmentsIndexImport
      parentRoute: typeof LayoutAssignmentsImport
    }
    '/_layout/attempts/': {
      preLoaderRoute: typeof LayoutAttemptsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/quizzes/': {
      preLoaderRoute: typeof LayoutQuizzesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/attempts/$attemptId/responses': {
      preLoaderRoute: typeof LayoutAttemptsAttemptIdResponsesImport
      parentRoute: typeof LayoutAttemptsAttemptIdImport
    }
    '/_layout/quizzes/$quizId/take': {
      preLoaderRoute: typeof LayoutQuizzesQuizIdTakeImport
      parentRoute: typeof LayoutQuizzesQuizIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutAssignmentsRoute.addChildren([
      LayoutAssignmentsAssignmentIdRoute,
      LayoutAssignmentsIndexRoute,
    ]),
    LayoutItemsRoute,
    LayoutKnowledgeAreasRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
    LayoutAttemptsAttemptIdRoute.addChildren([
      LayoutAttemptsAttemptIdResponsesRoute,
    ]),
    LayoutQuizzesQuizIdRoute.addChildren([LayoutQuizzesQuizIdTakeRoute]),
    LayoutAttemptsIndexRoute,
    LayoutQuizzesIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
