from sqlmodel import SQLModel  # noqa

from .attempt import (
    AssignmentCreate,
    AssignmentRead,
    AssignmentsPublic,
    AttemptCreate,
    AttemptRead,
    AttemptsPublic,
    AttemptUpdate,
    QuizAssignment,
    ResponseCreate,
    ResponseRead,
    ResponsesPublic,
    StudentAttempt,
    StudentResponse,
)
from .base import TimestampMixin
from .class_model import StudyClass, StudyClassEnrollment
from .common import Message, Token, TokenPayload
from .feedback import (
    AIFeedback,
    FeedbackCreate,
    FeedbackRead,
    FeedbacksPublic,
    LearningResource,
    ResourceCreate,
    ResourceRead,
    ResourcesPublic,
)
from .item import Item, ItemCreate, ItemPublic, ItemsPublic, ItemUpdate
from .quiz import (
    AreasPublic,
    KnowledgeArea,
    KnowledgeAreaRead,
    OptionCreate,
    OptionRead,
    OptionsPublic,
    OptionUpdate,
    QuestionCreate,
    QuestionOption,
    QuestionRead,
    QuestionsPublic,
    QuestionUpdate,
    Quiz,
    QuizCreate,
    QuizQuestion,
    QuizRead,
    QuizzesPublic,
    QuizUpdate,
)
from .user import (
    NewPassword,
    UpdatePassword,
    User,
    UserCreate,
    UserPublic,
    UserRegister,
    UsersPublic,
    UserUpdate,
    UserUpdateMe,
)

__all__ = [
    # User models
    "User",
    "UserCreate",
    "UserPublic",
    "UsersPublic",
    "UserUpdate",
    "UpdatePassword",
    "NewPassword",
    "UserRegister",
    "UserUpdateMe",
    # Item models
    "Item",
    "ItemCreate",
    "ItemPublic",
    "ItemsPublic",
    "ItemUpdate",
    "Message",
    "Token",
    "TokenPayload",
    # Quiz models
    "Quiz",
    "QuizCreate",
    "QuizUpdate",
    "QuizRead",
    "QuizzesPublic",
    "QuizQuestion",
    "QuestionCreate",
    "QuestionUpdate",
    "QuestionRead",
    "QuestionsPublic",
    "QuestionOption",
    "OptionCreate",
    "OptionUpdate",
    "OptionRead",
    "OptionsPublic",
    "KnowledgeArea",
    "KnowledgeAreaRead",
    "AreasPublic",
    # Class models
    "StudyClass",
    "StudyClassEnrollment",
    # Attempt models
    "QuizAssignment",
    "AssignmentCreate",
    "AssignmentRead",
    "AssignmentsPublic",
    "StudentAttempt",
    "AttemptCreate",
    "AttemptUpdate",
    "AttemptRead",
    "AttemptsPublic",
    "StudentResponse",
    "ResponseCreate",
    "ResponseRead",
    "ResponsesPublic",
    # Feedback models
    "AIFeedback",
    "FeedbackCreate",
    "FeedbackRead",
    "FeedbacksPublic",
    "LearningResource",
    "ResourceCreate",
    "ResourceRead",
    "ResourcesPublic",
    "TimestampMixin",
]
