"""add explanation to quiz_question

Revision ID: 13b14a13108e
Revises: 20a6e5cb0599
Create Date: 2025-05-21 17:08:41.576857

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "13b14a13108e"
down_revision = "20a6e5cb0599"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz_question",
        sa.Column("explanation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz_question", "explanation")
    # ### end Alembic commands ###
