"""Add started_at field to student_attempt table

Revision ID: 20a6e5cb0599
Revises: db980370cf04
Create Date: 2025-05-21 16:09:58.728395

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "20a6e5cb0599"
down_revision = "db980370cf04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("knowledge_area_name_key", "knowledge_area", type_="unique")
    op.add_column(
        "student_attempt", sa.Column("started_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student_attempt", "started_at")
    op.create_unique_constraint(
        "knowledge_area_name_key",
        "knowledge_area",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
