# Generated by Django 4.0.8 on 2022-10-28 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.TextField()),
                ('country', models.TextField()),
                ('looks', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Could be Better'), (4, 'Alright'), (5, 'Good'), (6, 'Very Good'), (7, 'Incredible')])),
                ('accessibility', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Could be Better'), (4, 'Alright'), (5, 'Good'), (6, 'Very Good'), (7, 'Incredible')])),
                ('usability', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Could be Better'), (4, 'Alright'), (5, 'Good'), (6, 'Very Good'), (7, 'Incredible')])),
                ('future_use', models.BooleanField()),
                ('recommend', models.BooleanField()),
                ('comments', models.TextField()),
            ],
            options={
                'verbose_name': 'feedback form',
                'verbose_name_plural': 'feedback forms',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%D/')),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Spam'), (2, 'Offensive'), (3, 'Misleading')])),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_type', models.PositiveSmallIntegerField(choices=[(1, 'Upvote'), (2, 'Downvote')])),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
