# Generated by Django 4.0.8 on 2022-10-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, default='Student', max_length=100)),
                ('biography', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Data',
                'verbose_name_plural': 'Users Data',
            },
        ),
        migrations.CreateModel(
            name='UniversityCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('ects', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_courses', to='users_metadata.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='SkillData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('skill', models.CharField(max_length=200)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_data', to='users_metadata.userdata')),
            ],
            options={
                'verbose_name': 'Skill Data',
                'verbose_name_plural': 'Skill Data',
            },
        ),
        migrations.CreateModel(
            name='ExternalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_profiles', to='users_metadata.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='defaults/experience.jpg', upload_to='experience_image/%Y/%m/%D/')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_data', to='users_metadata.userdata')),
            ],
            options={
                'verbose_name': 'experience data',
                'verbose_name_plural': 'experience data',
            },
        ),
        migrations.CreateModel(
            name='EducationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='defaults/university.jpg', upload_to='education_image/%Y/%m/%D/')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_data', to='users_metadata.userdata')),
            ],
            options={
                'verbose_name': 'education data',
                'verbose_name_plural': 'education data',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='certification_proof/%Y/%m/%D/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='users_metadata.userdata')),
            ],
        ),
    ]
