# Generated by Django 4.0.8 on 2022-10-28 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cv/%Y/%m/%d/')),
                ('motivation_letter', models.FileField(upload_to='motivation_letter/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('hours_per_week', models.DecimalField(decimal_places=1, max_digits=3)),
                ('salary_per_month', models.PositiveIntegerField()),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('requirements', models.TextField(blank=True)),
                ('you_do', models.TextField(blank=True)),
                ('we_offer', models.TextField(blank=True)),
                ('employment_details', models.TextField(blank=True)),
                ('category', models.IntegerField(choices=[(1, 'Administrative'), (2, 'Arts & Design'), (3, 'Business'), (4, 'Consulting'), (5, 'Customer Services & Support'), (6, 'Education'), (7, 'Engineering'), (8, 'Finance & Accounting'), (9, 'Healthcare'), (10, 'Human Resources'), (11, 'Information Technology'), (12, 'Legal'), (13, 'Marketing'), (14, 'Media & Communications'), (15, 'Military & Protective Services'), (16, 'Operations'), (17, 'Other'), (18, 'Product & Project Management'), (19, 'Research & Science'), (20, 'Retail & Food Services'), (21, 'Sales'), (22, 'Skilled Labor & Manufacturing'), (23, 'Transportation')])),
                ('type', models.IntegerField(choices=[(1, 'Full-time'), (2, 'Part-time'), (3, 'Contract'), (4, 'Temporary'), (5, 'Internship')])),
            ],
        ),
    ]
