// This file is auto-generated by @hey-api/openapi-ts

/**
 * Answer data for response details
 */
export type AnswerData = {
  type: string
  answer:
    | string
    | {
        [key: string]: unknown
      }
  is_correct: boolean
  created_at: string
}

/**
 * Paginated knowledge areas response
 */
export type AreasPublic = {
  data: Array<KnowledgeAreaRead>
  count: number
}

/**
 * Schema for quiz assignment creation
 */
export type AssignmentCreate = {
  quiz_id: number
  student_id: number
  class_id?: number | null
  due_date?: string | null
}

/**
 * Response schema for quiz assignments
 */
export type AssignmentRead = {
  quiz_id: number
  student_id: number
  class_id?: number | null
  due_date?: string | null
  id: number
}

/**
 * Paginated assignments response
 */
export type AssignmentsPublic = {
  data: Array<AssignmentRead>
  count: number
}

/**
 * Schema for student attempt creation from API
 */
export type AttemptCreateApiSchema = {
  quiz_id: number
  assignment_id?: number | null
  is_completed?: boolean
}

/**
 * Response schema for student attempts
 */
export type AttemptRead = {
  student_id: number
  quiz_id: number
  assignment_id?: number | null
  is_completed?: boolean
  id: number
  started_at?: string | null
  completed_at?: string | null
  score?: number | null
}

/**
 * Complete attempt with detailed responses
 */
export type AttemptResponsesDetailed = {
  attempt: AttemptSummary
  responses: Array<EnhancedResponse>
}

/**
 * Paginated attempts response
 */
export type AttemptsPublic = {
  data: Array<AttemptRead>
  count: number
}

/**
 * Summary data for an attempt
 */
export type AttemptSummary = {
  id: number
  is_completed: boolean
  score: number
  total_questions: number
  correct_answers: number
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

/**
 * Detailed response with question and answer information
 */
export type EnhancedResponse = {
  id: number
  question: QuestionData
  answer: AnswerData
  explanation?: string | null
}

/**
 * Schema for AI feedback creation
 */
export type FeedbackCreate = {
  response_id: number
  feedback_text: string
  error_type?: Array<string> | null
  confidence_score?: number | null
  feedback_content?: {
    [key: string]: unknown
  }
  ai_metadata?: {
    [key: string]: unknown
  } | null
}

/**
 * Response schema for AI feedback
 */
export type FeedbackRead = {
  response_id: number
  feedback_text: string
  error_type?: Array<string> | null
  confidence_score?: number | null
  feedback_content?: {
    [key: string]: unknown
  }
  ai_metadata?: {
    [key: string]: unknown
  } | null
  id: number
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

/**
 * Response schema for knowledge areas
 */
export type KnowledgeAreaRead = {
  name: string
  description?: string | null
  id: number
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

/**
 * Schema for option creation
 */
export type OptionCreate = {
  question_id: number
  text: string
  is_correct?: boolean
  order_position?: number
}

/**
 * Option data for response details
 */
export type OptionData = {
  id: number
  text: string
  is_correct: boolean
}

/**
 * Response schema for options
 */
export type OptionRead = {
  question_id: number
  text: string
  is_correct?: boolean
  order_position?: number
  id: number
}

/**
 * Paginated options response
 */
export type OptionsPublic = {
  data: Array<OptionRead>
  count: number
}

/**
 * Schema for option update
 */
export type OptionUpdate = {
  text?: string | null
  is_correct?: boolean | null
  order_position?: number | null
}

/**
 * Schema for question creation
 */
export type QuestionCreate = {
  quiz_id: number
  area_id?: number | null
  text: string
  question_type: string
  order_position?: number
  correct_answer?: string | null
  model_answer?: string | null
  explanation?: string | null
  difficulty?: string | null
  key_concepts?: {
    [key: string]: unknown
  } | null
  ai_guidance?: {
    [key: string]: unknown
  } | null
}

/**
 * Question data for response details
 */
export type QuestionData = {
  id: number
  text: string
  question_type: string
  model_answer?: string | null
  options?: Array<OptionData> | null
}

/**
 * Response schema for questions
 */
export type QuestionRead = {
  quiz_id: number
  area_id?: number | null
  text: string
  question_type: string
  order_position?: number
  correct_answer?: string | null
  model_answer?: string | null
  explanation?: string | null
  difficulty?: string | null
  key_concepts?: {
    [key: string]: unknown
  } | null
  ai_guidance?: {
    [key: string]: unknown
  } | null
  id: number
}

/**
 * Paginated questions response
 */
export type QuestionsPublic = {
  data: Array<QuestionRead>
  count: number
}

/**
 * Schema for question update
 */
export type QuestionUpdate = {
  area_id?: number | null
  text?: string | null
  question_type?: string | null
  order_position?: number | null
  correct_answer?: string | null
  model_answer?: string | null
  difficulty?: string | null
  key_concepts?: {
    [key: string]: unknown
  } | null
  ai_guidance?: {
    [key: string]: unknown
  } | null
}

/**
 * Schema for quiz creation
 */
export type QuizCreate = {
  title: string
  instructions?: string | null
  area_id?: number | null
  is_active?: boolean
}

/**
 * Response schema for quizzes
 */
export type QuizRead = {
  title: string
  instructions?: string | null
  area_id?: number | null
  is_active?: boolean
  id: number
  creator_id: number
}

/**
 * Schema for quiz update
 */
export type QuizUpdate = {
  title?: string | null
  instructions?: string | null
  area_id?: number | null
  is_active?: boolean | null
}

/**
 * Paginated quizzes response
 */
export type QuizzesPublic = {
  data: Array<QuizRead>
  count: number
}

/**
 * Schema for learning resource creation
 */
export type ResourceCreate = {
  feedback_id: number
  title: string
  description?: string | null
  url?: string | null
  resource_type: string
  area_id?: number | null
  relevance_score?: number | null
}

/**
 * Response schema for learning resources
 */
export type ResourceRead = {
  feedback_id: number
  title: string
  description?: string | null
  url?: string | null
  resource_type: string
  area_id?: number | null
  relevance_score?: number | null
  id: number
}

/**
 * Schema for student response creation
 */
export type ResponseCreate = {
  attempt_id: number
  question_id: number
  answer_text: string
  is_correct?: boolean | null
  selected_option_id?: number | null
}

/**
 * Response schema for student responses
 */
export type ResponseRead = {
  attempt_id: number
  question_id: number
  answer_text: string
  is_correct?: boolean | null
  selected_option_id?: number | null
  id: number
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  is_staff?: boolean
  full_name?: string | null
  role?: string
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  is_staff?: boolean
  full_name?: string | null
  role?: string
  id: number
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  is_staff?: boolean
  full_name?: string | null
  role?: string
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type AreasReadAreasData = {
  limit?: number
  skip?: number
}

export type AreasReadAreasResponse = AreasPublic

export type AssignmentsReadAssignmentsData = {
  limit?: number
  skip?: number
}

export type AssignmentsReadAssignmentsResponse = AssignmentsPublic

export type AssignmentsCreateAssignmentData = {
  requestBody: AssignmentCreate
}

export type AssignmentsCreateAssignmentResponse = AssignmentRead

export type AssignmentsReadAssignmentData = {
  assignmentId: number
}

export type AssignmentsReadAssignmentResponse = AssignmentRead

export type AssignmentsReadUserAssignmentsData = {
  limit?: number
  skip?: number
}

export type AssignmentsReadUserAssignmentsResponse = AssignmentsPublic

export type AttemptsReadAttemptsData = {
  limit?: number
  skip?: number
}

export type AttemptsReadAttemptsResponse = AttemptsPublic

export type AttemptsCreateAttemptData = {
  requestBody: AttemptCreateApiSchema
}

export type AttemptsCreateAttemptResponse = AttemptRead

export type AttemptsReadAttemptData = {
  attemptId: number
}

export type AttemptsReadAttemptResponse = AttemptRead

export type AttemptsCompleteAttemptData = {
  attemptId: number
  score?: number | null
}

export type AttemptsCompleteAttemptResponse = AttemptRead

export type AttemptsReadUserAttemptsData = {
  limit?: number
  skip?: number
}

export type AttemptsReadUserAttemptsResponse = AttemptsPublic

export type FeedbackCreateFeedbackData = {
  requestBody: FeedbackCreate
}

export type FeedbackCreateFeedbackResponse = FeedbackRead

export type FeedbackReadFeedbackData = {
  feedbackId: number
}

export type FeedbackReadFeedbackResponse = FeedbackRead

export type FeedbackReadFeedbackByResponseData = {
  /**
   * ID of the response to get feedback for
   */
  responseId: number
}

export type FeedbackReadFeedbackByResponseResponse = FeedbackRead | null

export type FeedbackRequestFeedbackGenerationData = {
  responseId: number
}

export type FeedbackRequestFeedbackGenerationResponse = {
  [key: string]: unknown
}

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type OptionsCreateOptionData = {
  requestBody: OptionCreate
}

export type OptionsCreateOptionResponse = OptionRead

export type OptionsReadOptionData = {
  optionId: number
}

export type OptionsReadOptionResponse = OptionRead

export type OptionsPartiallyUpdateOptionData = {
  optionId: number
  requestBody: OptionUpdate
}

export type OptionsPartiallyUpdateOptionResponse = OptionRead

export type OptionsDeleteOptionData = {
  optionId: number
}

export type OptionsDeleteOptionResponse = undefined

export type OptionsReadOptionsByQuestionData = {
  limit?: number
  /**
   * ID of the question to get options for
   */
  questionId: number
  skip?: number
}

export type OptionsReadOptionsByQuestionResponse = OptionsPublic

export type QuestionsCreateQuestionData = {
  requestBody: QuestionCreate
}

export type QuestionsCreateQuestionResponse = QuestionRead

export type QuestionsReadQuestionsByQuizData = {
  limit?: number
  /**
   * ID of the quiz to get questions for
   */
  quizId: number
  skip?: number
}

export type QuestionsReadQuestionsByQuizResponse = QuestionsPublic

export type QuestionsReadQuestionData = {
  questionId: number
}

export type QuestionsReadQuestionResponse = QuestionRead

export type QuestionsPartiallyUpdateQuestionData = {
  questionId: number
  requestBody: QuestionUpdate
}

export type QuestionsPartiallyUpdateQuestionResponse = QuestionRead

export type QuestionsDeleteQuestionData = {
  questionId: number
}

export type QuestionsDeleteQuestionResponse = undefined

export type QuizzesReadQuizzesData = {
  limit?: number
  skip?: number
}

export type QuizzesReadQuizzesResponse = QuizzesPublic

export type QuizzesCreateQuizData = {
  requestBody: QuizCreate
}

export type QuizzesCreateQuizResponse = QuizRead

export type QuizzesReadQuizData = {
  quizId: number
}

export type QuizzesReadQuizResponse = QuizRead

export type QuizzesUpdateQuizData = {
  quizId: number
  requestBody: QuizUpdate
}

export type QuizzesUpdateQuizResponse = QuizRead

export type QuizzesDeleteQuizData = {
  quizId: number
}

export type QuizzesDeleteQuizResponse = undefined

export type QuizzesReadUserQuizzesData = {
  limit?: number
  skip?: number
}

export type QuizzesReadUserQuizzesResponse = QuizzesPublic

export type RecommendationsCreateRecommendationData = {
  requestBody: ResourceCreate
}

export type RecommendationsCreateRecommendationResponse = ResourceRead

export type RecommendationsReadRecommendationData = {
  resourceId: number
}

export type RecommendationsReadRecommendationResponse = ResourceRead

export type RecommendationsReadRecommendationsByFeedbackData = {
  /**
   * ID of the feedback to get recommendations for
   */
  feedbackId: number
  limit?: number
  skip?: number
}

export type RecommendationsReadRecommendationsByFeedbackResponse =
  Array<ResourceRead>

export type ResponsesCreateResponseData = {
  requestBody: ResponseCreate
}

export type ResponsesCreateResponseResponse = ResponseRead

export type ResponsesReadResponseData = {
  responseId: number
}

export type ResponsesReadResponseResponse = ResponseRead

export type ResponsesReadResponsesByAttemptData = {
  /**
   * ID of the attempt to get responses for
   */
  attemptId: number
  limit?: number
  skip?: number
}

export type ResponsesReadResponsesByAttemptResponse = AttemptResponsesDetailed

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: number
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: number
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: number
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
